version: "3"
services:
  env:
    build: .
    tty: true
    command: bin/bash
    container_name: oneclick_env
  nginx_pm:
    image: nginx:1.13.5
    ports:
        - 3000:80
    volumes:
        - ./conf.d:/etc/nginx/conf.d
    networks:
        - env_network
    depends_on:
        - env
networks:
    env_network:
        driver: bridge
