apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: {{NAME_OF_IMAGE}}
          imagePullPolicy: Always
          name: flask-app
          ports:
            - containerPort: 5000
